version: 2.1

jobs:
  Run Automation Testcases:
    machine:
      image: ubuntu-2204:current
    docker:
      - image: cimg/openjdk:23.0.1
    steps:
      - run: |
          java --version

workflows:
  my-workflow:
    jobs:
      - Run Automation Testcases