version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo apt-get update
            sudo apt install openjdk-19-jdk
      - run:
          name: Verify Java installation
          command: java -version
      - run:
          name: Install Maven
          command: sudo apt-get install maven
      - run:
          name: Verify Maven installation
          command: mvn --version
      - browser-tools/install-chrome
      - run:
          name: Verify Chrome installation
          command: google-chrome --version
      - install dependencies
      - run:
          name: install dependencies
          command: mvn clean install -DskipTests
      - Run test cases
      - run:
          name: Run test cases
          command: mvn test -DsuiteXmlFile=target/surefire-reports/testng-failed.xml

workflows:
  build-and-test:
    jobs:
      - build-and-test