version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Verify Chrome installation
          command: google-chrome --version
      - run:
          name: Install Dependencies
          command: mvn clean install -DskipTests
      - run:
          name: Run test cases
          command: mvn test

workflows:
  build-and-test:
    jobs:
      - build-and-test