version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Run test cases
          command: |
            export BROWSER=chrome
            export HEADLESS=true
            export ENV=Test
            mvn test -X -DsuiteXmlFile=target/surefire-reports/testng-failed.xml

workflows:
  build-and-test:
    jobs:
      - build-and-test