version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:22.0.2
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Run test cases
          command: |
            export BROWSER=chrome
            export HEADLESS=true
            export ENV=Test
            mvn test -X -DsuiteXmlFile=testng.xml -Dexec.skip=true
      - store_test_results:
          path: target/surefire-reports/My Test Suite/

workflows:
  build-and-test:
    jobs:
      - build-and-test