name: Manual workflow for automation testcases

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment'
        required: true
        default: 'Test'
        type: choice
        options:
          - Test
          - Stage
      Browser:
        description: 'Browser'
        required: true
        default: 'Chrome'
        type: choice
        options:
          - Chrome
          - Firefox
          - Edge
      Email:
        description: 'Please enter Email to receive result'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: 23
          distribution: 'temurin'

      - name: Set up Chrome
        if: ${{ github.event.inputs.Browser == 'chrome' }}
        uses: browser-actions/setup-chrome@v1.7.2

      - name: Set up Firefox
        if: ${{ github.event.inputs.Browser == 'firefox' }}
        uses: browser-actions/setup-firefox@v1.5.2

      - name: Setup Edge
        if: ${{ github.event.inputs.Browser == 'edge' }}
        uses: browser-actions/setup-edge@v1.1.1

      - name: Install dependencies without running tests
        run: mvn clean install -DskipTests

      - name: Run tests
        id: Run_Test
        run: |
          export BROWSER=${{ github.event.inputs.Browser }}
          export HEADLESS=true
          export ENV=${{ github.event.inputs.Environment }}
          mvn test -DsuiteXmlFile=testng.xml

      - name: Send result via email
        if: always()
        run: |
          export EMAIL=${{ github.event.inputs.Email }}
          export SUBJECT="Complete Execution for ${{ github.event.inputs.Environment }} Environment on ${{ github.event.inputs.Browser }} Browser"
          mvn exec:java
        env:
          EMAIL_USER: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}

      - name: Store Html Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Initial Test Result
          path: target/html-report/SparkReport.html

      - name: Re-run failed tests
        id: Re_Run_Test
        if: ${{ failure() && steps.Run_Test.outcome == 'failure' }}
        run: |
          export BROWSER=${{ github.event.inputs.Browser }}
          export HEADLESS=true
          export Is_Flaky=true
          export ENV=${{ github.event.inputs.Environment }}
          mvn test -DsuiteXmlFile=target/surefire-reports/testng-failed.xml

      - name: Re-send result via email
        if: ${{ failure() && steps.Run_Test.outcome == 'failure' }}
        run: |
          export EMAIL=${{ github.event.inputs.Email }}
          export SUBJECT="Re-run Failed Test Cases for ${{ github.event.inputs.Environment }} Environment on ${{ github.event.inputs.Browser }} Browser"
          mvn exec:java
        env:
          EMAIL_USER: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}

      - name: Store Html Report
        if: ${{ failure() && steps.Run_Test.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: Re-Run Test Result
          path: target/html-report/SparkReport.html

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Report
          path: target/surefire-reports/junitreports/*.xml
          reporter: java-junit
