name: manual workflow

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment'
        required: true
        default: 'Test'
        type: choice
        options:
          - Test
          - Stage
      Browser:
        description: 'Browser'
        required: true
        default: 'Chrome'
        type: choice
        options:
          - Chrome
          - Firefox
          - Edge
      Email:
        description: 'Please enter Email to receive result'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.3.0
        with:
          java-version: 22
          distribution: 'temurin'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5

      - name: Set up Chrome
        if: ${{ github.event.inputs.Browser == 'chrome' }}
        uses: browser-actions/setup-chrome@v1.7.2

      - name: Set up Firefox
        if: ${{ github.event.inputs.Browser == 'firefox' }}
        uses: browser-actions/setup-firefox@v1.5.2

      - name: Set up Edge
        if: ${{ github.event.inputs.Browser == 'edge' }}
        uses: browser-actions/setup-edge@v1.1.1

      - name: Setup Chrome WebDriver
        if: ${{ github.event.inputs.Browser == 'chrome' }}
        uses: browser-actions/setup-chrome@v1.7.2

      - name: Setup Firefox WebDriver
        if: ${{ github.event.inputs.Browser == 'firefox' }}
        uses: browser-actions/setup-firefox@v1.5.2

      - name: Setup Edge WebDriver
        if: ${{ github.event.inputs.Browser == 'edge' }}
        uses: browser-actions/setup-edge@v1.1.1

      - name: Install dependencies without running tests
        run: mvn clean install -DskipTests

      - name: Run tests
        id: Run_Test
        run: |
          export BROWSER=${{ github.event.inputs.Browser }}
          export HEADLESS=true
          export ENV=${{ github.event.inputs.Environment }}
          mvn test -DsuiteXmlFile=testng.xml

      - name: Send result via email
        if: always()
        run: |
          export EMAIL=${{ github.event.inputs.Email }}
          export SUBJECT="Complete Execution for ${{ github.event.inputs.Environment }} on ${{ github.event.inputs.Browser }}"
          mvn exec:java
        env:
          EMAIL_USER: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}

      - name: Re-run failed tests
        id: Re_Run_Test
        if: ${{ failure() && steps.Run_Test.outcome == 'failure' }}
        run: |
          export BROWSER=${{ github.event.inputs.Browser }}
          export HEADLESS=true
          export ENV=${{ github.event.inputs.Environment }}
          mvn test -DsuiteXmlFile=target/surefire-reports/testng-failed.xml

      - name: Re-send result via email
        if: ${{ failure() && steps.Run_Test.outcome == 'failure' }}
        run: |
          export EMAIL=${{ github.event.inputs.Email }}
          export SUBJECT="Re-run Failed Test Cases for ${{ github.event.inputs.Environment }} on ${{ github.event.inputs.Browser }}"
          mvn exec:java
        env:
          EMAIL_USER: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}